sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t chrisbabu/docker_react -f Dockerfile.dev .

script:
    - docker run -e CI=true chrisbabu/docker_react npm run test